name: Nx Build

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js 20.1.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.1.0

    - name: Setup env
      run: |
        npm i -g npm@9.6.6
        npm ci
        
    - name: Build
      run: yarn build
